spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=main;encrypt=true;trustServerCertificate=true
    username: testUser
    password: testPassword
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  test:
    datasource:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:tc:sqlserver:latest://hostname:port;databaseName=testdb
    jpa:
      hibernate:
        ddl-auto: create
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
  websocket:
    broker:
      relay-host: localhost
      relay-port: 61613
      relay-login: guest
      relay-passcode: guest
      virtual-host: /
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    locations: /resources/migration/
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG